"""Add tables

Revision ID: cacf34a2f7f2
Revises: 248fbfe884f0
Create Date: 2026-04-24 23:22:28.649616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacf34a2f7f2'
down_revision: Union[str, Sequence[str], None] = '248fbfe884f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandeiras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('custo_adicional', sa.Float(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('data_atualizacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_consumo', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('tarifa_fixa', sa.Float(), nullable=True),
    sa.Column('faixas', sa.JSON(), nullable=True),
    sa.Column('adicional_esgoto', sa.Float(), nullable=True),
    sa.Column('data_atualizacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarifas_tipo_consumo'), 'tarifas', ['tipo_consumo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_consumo', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('simulacao', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumos_tipo_consumo'), 'consumos', ['tipo_consumo'], unique=False)
    op.create_table('dicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_consumo', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dicas_tipo_consumo'), 'dicas', ['tipo_consumo'], unique=False)
    op.create_table('metas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('tipo_consumo', sa.String(), nullable=True),
    sa.Column('quantidade_alvo', sa.Float(), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_local'), 'metas', ['local'], unique=False)
    op.create_index(op.f('ix_metas_tipo_consumo'), 'metas', ['tipo_consumo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metas_tipo_consumo'), table_name='metas')
    op.drop_index(op.f('ix_metas_local'), table_name='metas')
    op.drop_table('metas')
    op.drop_index(op.f('ix_dicas_tipo_consumo'), table_name='dicas')
    op.drop_table('dicas')
    op.drop_index(op.f('ix_consumos_tipo_consumo'), table_name='consumos')
    op.drop_table('consumos')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tarifas_tipo_consumo'), table_name='tarifas')
    op.drop_table('tarifas')
    op.drop_table('bandeiras')
    # ### end Alembic commands ###
