import { StyleSheet } from "react-native";
import { temas } from "../../global/themes";

export const style = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    header: {
        height: 140,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    botão_menu: {
        padding: 10,
    },
    menuIcon: {
        width: 24,
        height: 18,
        justifyContent: 'space-between',
    },
    menuLine: {
        width: 24,
        height: 3,
        backgroundColor: '#FFFFFF',
        borderRadius: 2,
    },
    headerText: {
        marginLeft: 20,
    },
    título: {
        fontSize: 24,
        color: '#FFFFFF',
        fontFamily: temas.fonts.bold,
    },
    subtítulo: {
        fontSize: 14,
        color: '#FFFFFF',
        opacity: 0.9,
        fontFamily: temas.fonts.regular,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    cardsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
card: {
    width: 100,
    height: 100,
    borderRadius: 15,
    paddingVertical: 6,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
},

    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    cardHeaderText: {
        fontSize: 12,
        color: '#FFFFFF',
        fontFamily: temas.fonts.regular,
        opacity: 0.8
    },
cardValue: {
    fontSize: 15,
    color: '#FFFFFF',
    fontFamily: temas.fonts.bold,
    lineHeight: 18,
    marginBottom: 1,
},
cardPrecoMenu: {
    fontSize: 15,
    color: '#FFFFFF',
    fontFamily: temas.fonts.bold,
    lineHeight: 13,
    marginBottom: 2,
},
cardLabel: {
    fontSize: 12,
    color: '#FFFFFF',
    fontFamily: temas.fonts.regular,
    opacity: 0.8,
    marginTop: 3,
},
    divisório: {
        width: '100%',
        height: 1,
        backgroundColor: '#E0E0E0',
        marginVertical: 15,
    },
    sectionTitle: {
        fontSize: 18,
        color: '#9E9E9E',
        fontFamily: temas.fonts.medium,
        marginBottom: 15,
    },
    progressContainer: {
        width: '100%',
        height: 40,
        backgroundColor: '#E0E0E0',
        borderRadius: 20,
        padding: 5,
        marginBottom: 10,
    },
    progressBar: {
        width: '100%',
        height: '100%',
        backgroundColor: '#BDBDBD',
        borderRadius: 15,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#66BB6A',
        borderRadius: 15,
    },
    tipsCard: {
        width: '100%',
        backgroundColor: '#66BB6A',
        borderRadius: 20,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    tipsIcon: {
        marginRight: 15,
    },
    tipsContent: {
        flex: 1,
    },
    tipsTitle: {
        fontSize: 18,
        color: '#FFFFFF',
        fontFamily: temas.fonts.bold,
        marginBottom: 8,
    },
    tipsText: {
        fontSize: 14,
        color: '#FFFFFF',
        fontFamily: temas.fonts.regular,
        lineHeight: 20,
    },
    buttonConsumo: {
        width: '100%',
        height: 50,
        backgroundColor: '#E0E0E0',
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    buttonConsumoText: {
        fontSize: 18,
        color: '#333333',
        fontFamily: temas.fonts.medium,
    },
    sectionContainer: {
        paddingVertical: 20,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyText: {
        fontSize: 16,
        color: '#999999',
        fontFamily: temas.fonts.regular,
        marginTop: 10,
    },
    preferenceItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    preferenceText: {
        fontSize: 16,
        color: '#333333',
        fontFamily: temas.fonts.medium,
    },
    toggle: {
        width: 50,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#E0E0E0',
    },
    aboutCard: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    aboutTitle: {
        fontSize: 24,
        color: '#2E7D32',
        fontFamily: temas.fonts.bold,
        marginTop: 15,
    },
    aboutVersion: {
        fontSize: 14,
        color: '#999999',
        fontFamily: temas.fonts.regular,
        marginTop: 5,
    },
    aboutText: {
        fontSize: 14,
        color: '#666666',
        fontFamily: temas.fonts.regular,
        textAlign: 'center',
        marginTop: 20,
        paddingHorizontal: 20,
        lineHeight: 20,
    },
    menuCardsContainer: {
        marginTop: 18,
        gap: 14,
    },
    menuCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        paddingVertical: 18,
        paddingHorizontal: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.10,
        shadowRadius: 6,
        shadowOffset: {
            width: 0,
            height: 3,
        },
    },
    menuCardLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    menuIconBox: {
        width: 52,
        height: 52,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    menuCardTitle: {
        fontSize: 18,
        color: '#333333',
        fontFamily: temas.fonts.bold,
    },
    menuCardSubtitle: {
        fontSize: 13,
        color: '#888888',
        marginTop: 3,
    },
        tipsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    badgeAnalise: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
    },
    badgeText: {
        color: '#2E7D32',
        fontSize: 10,
        fontWeight: 'bold',
    },
    analiseContainer: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.3)',
    },
    analiseRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    analiseLabel: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.8)',
    },
    analiseValue: {
        fontSize: 12,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    tipsDate: {
        fontSize: 10,
        color: 'rgba(255,255,255,0.7)',
        marginTop: 10,
        textAlign: 'right',
    },
});